name: SwiftLint

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654
        with:
          cache: false
      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml --config .swiftlint-ci.yml --reporter github-actions-logging .
