name: Validate localization files

on:
  workflow_call:
    secrets:
      LOCO_KEY:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654
        with:
          cache: false
      - name: Validate
        run: import_loco --check
        env:
          LOCO_API_KEY: ${{ secrets.LOCO_KEY }}
